---

output-format: text

ignore-paths:
  - tests/
  - pass_import/managers/__init__.py
  - pass_import/formats/__init__.py
  - pass_import/decrypters/__init__.py

ignore-patterns:
  - (^|/)\..+

pylint:
  disable:
    - invalid-name
    - too-many-ancestors
    - unspecified-encoding
    - consider-using-with

  options:
    max-locals: 17

pyroma:
  disable:
    - PYR06

mccabe:
  options:
    max-complexity: 15

pydocstyle:
  disable:
    - D100
    - D107
    - D203
    - D204
    - D213
    - E231
